name: Setup and Run Script

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add KiCad repository
      run: sudo add-apt-repository --yes ppa:kicad/kicad-8.0-releases

    - name: Update package lists
      run: sudo apt update

    - name: Install KiCad
      run: sudo apt install --install-recommends -y kicad

    - name: Run python script
      run: |
        python3 workflow.py